package parser

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/vsolanki12/codeatlas/internal/domain"
)

func TestGoParserFieldDefinitionsGeneratedAndResourceSignatures(t *testing.T) {
	repo := t.TempDir()
	if err := os.WriteFile(filepath.Join(repo, "go.mod"), []byte("module example.com/repo\n"), 0644); err != nil {
		t.Fatal(err)
	}
	source := `// Code generated by fixture. DO NOT EDIT.
package p
type Configuration struct {
 // AutoRepair enables replacement of unhealthy machines.
 AutoRepair bool
}
type MachineHealthCheck struct{}
func Reconcile(ctx, client interface{}) {
 object := &MachineHealthCheck{}
 client.Create(ctx, object)
 controllerutil.CreateOrUpdate(ctx, client, object, nil)
 controllerutil.CreateOrPatch(ctx, client, &MachineHealthCheck{}, nil)
 controllerutil.CreateOrUpdate(ctx, client, unknownObject(), nil)
}
`
	if err := os.WriteFile(filepath.Join(repo, "p.go"), []byte(source), 0644); err != nil {
		t.Fatal(err)
	}
	entities, err := NewGoParserForRepo(repo).Parse(domain.File{RelativePath: "p.go"})
	if err != nil {
		t.Fatal(err)
	}
	byID := make(map[string]domain.Entity)
	for _, entity := range entities {
		byID[entity.ID] = entity
		if !entity.Generated {
			t.Fatalf("generated header lost on %s", entity.ID)
		}
	}
	field := byID["field:example.com/repo.Configuration.AutoRepair"]
	if field.Kind != domain.KindField || field.Description != "AutoRepair enables replacement of unhealthy machines." || field.Source.Line != 4 || field.Source.EndLine != 5 {
		t.Fatalf("field definition = %+v", field)
	}
	fn := byID["function:example.com/repo.Reconcile"]
	if len(fn.CreateSites) != 3 {
		t.Fatalf("resolved create sites = %+v, want Create + two three-argument upserts", fn.CreateSites)
	}
	if len(fn.ResourceOperations) != 4 {
		t.Fatalf("operation observations = %+v, unresolved object must remain visible", fn.ResourceOperations)
	}
	if fn.ResourceOperations[3].ObjectType != "" {
		t.Fatalf("invented unknown operation type: %+v", fn.ResourceOperations[3])
	}
}

func TestFieldSourceSpanIncludesGoverningDocumentationAndTrailingComment(t *testing.T) {
	repo := t.TempDir()
	source := `package p
type Management struct {
 // AutoRepair enables automatic replacement.
 // Disabled pools retain unhealthy machines.
 // The default is false.
 AutoRepair bool /* API note:
 changing this field updates health checks.
 */
}
`
	if err := os.WriteFile(filepath.Join(repo, "management.go"), []byte(source), 0644); err != nil {
		t.Fatal(err)
	}
	entities, err := NewGoParserForRepo(repo).Parse(domain.File{RelativePath: "management.go"})
	if err != nil {
		t.Fatal(err)
	}
	for _, field := range entities {
		if field.Kind != domain.KindField || field.Name != "AutoRepair" {
			continue
		}
		if field.ID != "field:p.Management.AutoRepair" || field.Source.Line != 3 || field.Source.EndLine != 8 {
			t.Fatalf("field identity or documented source span changed incorrectly: %+v", field)
		}
		excerpt := strings.Join(strings.Split(source, "\n")[field.Source.Line-1:field.Source.EndLine], "\n")
		for _, required := range []string{"Disabled pools retain unhealthy machines.", "The default is false.", "AutoRepair bool", "changing this field updates health checks."} {
			if !strings.Contains(excerpt, required) {
				t.Fatalf("source-backed field excerpt omitted %q: %s", required, excerpt)
			}
		}
		return
	}
	t.Fatal("AutoRepair field was not extracted")
}
